using Azure;
using Azure.Search.Documents.Models;
using hackaton_microsoft_agro.Interface;
using static System.Net.Mime.MediaTypeNames;

namespace hackaton_microsoft_agro.Services
{
    public class Orchestrator(ContentSafety contentSafety,
                              CustomVision customVision,
                              AISearch aISearch,
                              OpenAIService openAI) : IOrchestrator
    {

        const string Observation = """"
            The recommendation can only be made by a qualified professional. An agronomic prescription must be issued. The information is researched and the response generated by generative AI and it is necessary to verify at the source whether the information is accurate.
            """";

        public Dictionary<string, string> ProcessRequest(string? query, byte[]? image)
        {
            string? pestClassification = null;

            // Validate content using Azure ContentSafety
            contentSafety.ValidateContent(image, query);

            // Perform Azure Custom Vision image classification if an image is provided
            if (image != null)
                (pestClassification, query) = AnalyseImage(image);

            // Check if the query is null or empty
            if (string.IsNullOrEmpty(query))
                  return CreateResponse(pestClassification, "No query.");

            // Perform Azure AI Search and OpenAI RAG
            var response = GetAISearchResponse(query);

            // Return final response
            return CreateResponse(pestClassification, response);
        }

        public (string pest, string query) AnalyseImage(byte[]? image)
        {
            string query = "";

            if (image == null)
                throw new ArgumentException("Image data is invalid.");

            (string pest, double confidence) = customVision.AnalyseImageContent(image);

            if (confidence >= 0.75)
                query = $"Suggest control for {pest}";
            else
                pest = "Unidentified";

            return (pest: pest, query: query);
        }

        private string GetAISearchResponse(string query)
        {
            var searchResults = aISearch.Search(query, 5);
            return openAI.ProcessResponse(query, string.Join(" ", searchResults));
        }

        private Dictionary<string, string> CreateResponse(string? pestResult, string response)
        {
            var result = new Dictionary<string, string>
            {
                ["result"] = response,
                ["observation"] = Observation
            };

            if (pestResult != null)
            {
                result["pestClassification"] = pestResult;
            }

            return result;
        }
    }
}
